project:
  title: "My Website (English)"
  output-dir: docs
  
website:
  navbar:
    left:
      - href: index.qmd        
        text: Home
      - href: software.qmd        
        text: Software
      - icon: book
        href: publications.qmd
        text: Publications
    right:
      - href: de/index.html
        text: Deutsch
      - href: index.html
        text: English
        
lang: en

format:
  html:
    theme: morph
    toc: true